Repository eunomia-bpf/bpftime, pull requests merged in 2023-11, with the labels that each got.

#71 docs: fix links for webpage
  README.md
Labels: size/M

#68 runtime: add kernel user perf event array and per cpu array
  .gitignore
  daemon/kernel/bpf_kernel_config.h
  daemon/kernel/bpf_tracer.bpf.c
  daemon/user/bpf_tracer.cpp
  daemon/user/bpftime_driver.cpp
  daemon/user/bpftime_driver.hpp
  daemon/user/daemon_config.hpp
  daemon/user/handle_bpf_event.cpp
  daemon/user/handle_bpf_event.hpp
  example/.gitignore
  runtime/CMakeLists.txt
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/shared/array_map_kernel_user.cpp
  runtime/src/bpf_map/shared/array_map_kernel_user.hpp
  runtime/src/bpf_map/shared/hash_map_kernel_user.cpp
  runtime/src/bpf_map/shared/hash_map_kernel_user.hpp
  runtime/src/bpf_map/shared/percpu_array_map_kernel_user.cpp
  runtime/src/bpf_map/shared/percpu_array_map_kernel_user.hpp
  runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
  runtime/src/bpf_map/shared/perf_event_array_kernel_user.hpp
  runtime/src/bpf_map/userspace/array_map.cpp
  runtime/src/bpf_map/userspace/array_map.hpp
  runtime/src/bpf_map/userspace/hash_map.cpp
  runtime/src/bpf_map/userspace/hash_map.hpp
  runtime/src/bpf_map/userspace/per_cpu_array_map.cpp
  runtime/src/bpf_map/userspace/per_cpu_array_map.hpp
  runtime/src/bpf_map/userspace/per_cpu_hash_map.cpp
  runtime/src/bpf_map/userspace/per_cpu_hash_map.hpp
  runtime/src/bpf_map/userspace/perf_event_array_map.cpp
  runtime/src/bpf_map/userspace/perf_event_array_map.hpp
  runtime/src/bpf_map/userspace/ringbuf_map.cpp
  runtime/src/bpf_map/userspace/ringbuf_map.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/epoll_handler.hpp
  runtime/src/handler/handler_manager.hpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/map_handler.hpp
  runtime/src/handler/prog_handler.hpp
  runtime/unit-test/maps/test_per_cpu_array.cpp
  runtime/unit-test/maps/test_per_cpu_hash.cpp
  runtime/unit-test/test_bpftime_shm_json.cpp
Labels: size/XXL

#70 daemon: add process exec tracing
  README.md
  daemon/bpf_tracer_event.h
  daemon/kernel/bpf_tracer.bpf.c
  daemon/user/bpf_tracer.cpp
  daemon/user/daemon_config.hpp
  daemon/user/handle_bpf_event.cpp
  daemon/user/handle_bpf_event.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/handler/perf_event_handler.cpp
Labels: size/L

#74 daemon: link librt (Fix issue #73)
  daemon/CMakeLists.txt
Labels: size/M

#78 Update examples CI (automatic test)
  .github/script/run_example.py
  .github/workflows/test-examples.yml
  example/libbpf-tools/bashreadline/readline.c
  example/libbpf-tools/gethostlatency/gethostlatency.c
  example/libbpf-tools/opensnoop/opensnoop.c
  example/libbpf-tools/statsnoop/statsnoop.c
  example/malloc/malloc.c
  example/opensnoop/opensnoop.c
  example/sslsniff/sslsniff.c
  tools/cli-rs/src/main.rs
Labels: size/L

#81 daemon: enable uprobe white list
  .gitignore
  daemon/kernel/bpf_tracer.bpf.c
  daemon/user/bpf_tracer.cpp
  daemon/user/bpftime_driver.cpp
  daemon/user/daemon_config.hpp
  daemon/user/main.cpp
  example/.gitignore
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_map/shared/hash_map_kernel_user.hpp
  runtime/src/bpf_map/shared/percpu_array_map_kernel_user.hpp
  runtime/src/handler/handler_manager.cpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/src/handler/perf_event_handler.hpp
  runtime/test/bpf/.gitignore
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/unit-test/attach/test_filter_attach.cpp
  runtime/unit-test/attach/test_replace_attach.cpp
  runtime/unit-test/attach/test_uprobe_uretprobe.cpp
  runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
  vm/llvm-jit/src/bpf_jit.cpp
Labels: size/L

#82 vm: fix lddw helper definition bug of `llvm-jit`
  example/.gitignore
  runtime/src/bpf_map/shared/array_map_kernel_user.cpp
  runtime/src/bpf_map/shared/array_map_kernel_user.hpp
  runtime/src/bpftime_prog.cpp
  runtime/src/bpftime_shm.cpp
  vm/llvm-jit/src/bpf_jit.cpp
  vm/llvm-jit/src/bpf_jit_compile_module.cpp
  vm/llvm-jit/src/bpf_jit_helpers.h
  vm/llvm-jit/src/ebpf_vm.cpp
Labels: size/M

#85 runtime: fix incorrect implementation in`bpftime_get_current_pid_tgid`
  runtime/src/bpf_helper.cpp
Labels: size/XS

#84 Update README.md
  README.md
Labels: size/S

#86 runtime: add mpk support
  .github/workflows/test-runtime.yml
  .gitignore
  .vscode/launch.json
  README.md
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_map/README.md
  runtime/src/bpftime_prog.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
Labels: size/L

#88 Fix a README.md typo
  README.md
Labels: size/XS

#89 Docs: Add acknowledgement and fix ci
  .github/workflows/test-runtime.yml
  README.md
Labels: size/M

#93 examples: add syscount
  .github/workflows/test-examples.yml
  example/libbpf-tools/syscount/.gitignore
  example/libbpf-tools/syscount/Makefile
  example/libbpf-tools/syscount/README.md
  example/libbpf-tools/syscount/errno_helpers.c
  example/libbpf-tools/syscount/errno_helpers.h
  example/libbpf-tools/syscount/maps.bpf.h
  example/libbpf-tools/syscount/syscall_helpers.c
  example/libbpf-tools/syscount/syscall_helpers.h
  example/libbpf-tools/syscount/syscount.bpf.c
  example/libbpf-tools/syscount/syscount.c
  example/libbpf-tools/syscount/syscount.h
  example/libbpf-tools/syscount/victim.cpp
Labels: size/XXL

#96 examples: add more minimal examples
  .github/workflows/test-examples.yml
  README.md
  example/minimal/.gitignore
  example/minimal/Makefile
  example/minimal/README.md
  example/minimal/filter_replace_attach.h
  example/minimal/syscall.bpf.c
  example/minimal/syscall.c
  example/minimal/ufilter.bpf.c
  example/minimal/ufilter.c
  example/minimal/uprobe.bpf.c
  example/minimal/uprobe.c
  example/minimal/ureplace.bpf.c
  example/minimal/ureplace.c
  example/minimal/victim.c
  example/patch/redis/.gitignore
  example/patch/redis/Makefile
  example/patch/redis/README.md
  example/patch/redis/ffi.bpf.h
  example/patch/redis/redis-patch.bpf.c
  example/patch/redis/redis-patch.c
  example/patch/redis/redis-server.h
  example/patch/vim/README.md
  example/patch/vim/poc.bpf.c
  runtime/include/bpftime_shm.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/perf_event_handler.hpp
  runtime/syscall-server/syscall_context.cpp
  runtime/unit-test/assets/filter.bpf.c
Labels: size/XL

#98 docs: add documents of how to use JIT
  daemon/kernel/bpf_tracer.bpf.c
  daemon/user/handle_bpf_event.cpp
  documents/usage.md
  example/sslsniff/README.md
  runtime/src/bpf_map/userspace/array_map.hpp
  runtime/src/bpf_map/userspace/hash_map.cpp
  runtime/src/bpf_map/userspace/hash_map.hpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/map_handler.hpp
Labels: size/L

#101 syscall_server: fix epoll_wait implementation
  .github/script/run_example.py
  runtime/src/bpftime_shm.cpp
  runtime/src/handler/perf_event_handler.hpp
Labels: size/L

#103 benchmark: add multi-thread bench driver
  README.md
  benchmark/Makefile
  benchmark/test.c
  documents/avaliable-features.md
  runtime/CMakeLists.txt
  runtime/agent-transformer/agent-transformer.cpp
  runtime/include/bpf_attach_ctx.hpp
  runtime/src/attach/attach_manager/base_attach_manager.hpp
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/attach/bpf_attach_syscall.cpp
  runtime/src/syscall_table.cpp
Labels: size/XL

#106 runtime: remove usage of weak_ptr in attach manager
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/src/attach/attach_manager/frida_attach_manager.hpp
  runtime/unit-test/attach/test_filter_attach.cpp
  runtime/unit-test/attach/test_replace_attach.cpp
  runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
Labels: size/L

#109 example: add funclatency from bcc/libbpf-tools
  .github/workflows/test-examples.yml
  example/libbpf-tools/funclatency/.gitignore
  example/libbpf-tools/funclatency/Makefile
  example/libbpf-tools/funclatency/bits.bpf.h
  example/libbpf-tools/funclatency/funclatency.bpf.c
  example/libbpf-tools/funclatency/funclatency.c
  example/libbpf-tools/funclatency/funclatency.h
  example/libbpf-tools/funclatency/victim.cpp
Labels: size/XL

#108 vm: fix compiling ebpf program using llvm in parallel environment
  .github/script/run_example.py
  .github/workflows/test-examples.yml
  Makefile
  vm/llvm-jit/src/bpf_jit.cpp
  vm/llvm-jit/src/bpf_jit_compile_module.cpp
  vm/llvm-jit/src/bpf_jit_helpers.h
  vm/llvm-jit/src/ebpf_vm.cpp
  vm/llvm-jit/src/llvm_jit_context.h
Labels: size/L

#110 example: add mountsnoop from libbpf-tools
  .github/script/run_example.py
  .github/workflows/test-examples.yml
  example/libbpf-tools/mountsnoop/.gitignore
  example/libbpf-tools/mountsnoop/Makefile
  example/libbpf-tools/mountsnoop/mountsnoop.bpf.c
  example/libbpf-tools/mountsnoop/mountsnoop.c
  example/libbpf-tools/mountsnoop/mountsnoop.h
  example/libbpf-tools/mountsnoop/victim.c
  runtime/src/syscall_table.cpp
Labels: size/XL

#111 runtime: add fs extended helpers
  example/error-inject/attach_override.h
  example/error-inject/error_inject.bpf.c
  example/error-inject/error_inject.c
  example/error-inject/error_inject_syscall.bpf.c
  example/error-inject/error_inject_syscall.c
  example/error-inject/victim.c
  example/fs-filter-cache/.gitignore
  example/fs-filter-cache/Makefile
  example/fs-filter-cache/README.md
  example/fs-filter-cache/fs-filter-cache.bpf.c
  example/fs-filter-cache/fs-filter-cache.c
  example/fs-filter-cache/fs-filter-cache.h
  example/fs-filter-cache/victim.cpp
  runtime/include/bpftime_ffi.hpp
  runtime/src/bpf_helper.cpp
Labels: size/L

#113 example: add sigsnoop from libbpf-tools
  .github/workflows/test-examples.yml
  example/libbpf-tools/sigsnoop/.gitignore
  example/libbpf-tools/sigsnoop/Makefile
  example/libbpf-tools/sigsnoop/sigsnoop.bpf.c
  example/libbpf-tools/sigsnoop/sigsnoop.c
  example/libbpf-tools/sigsnoop/sigsnoop.h
  example/libbpf-tools/sigsnoop/victim.cpp
Labels: size/XL

#114 daemon: fix config from env
  daemon/kernel/bpf_tracer.bpf.c
  daemon/user/bpftime_driver.cpp
  runtime/include/bpftime_shm.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/bpftime_shm_json.cpp
  runtime/syscall-server/syscall_server_utils.cpp
  tools/bpftimetool/main.cpp
  tools/bpftimetool/minimal.json
Labels: size/L
