Repository eunomia-bpf/bpftime, pull requests merged in 2023-10, with the labels that each got.

#17 ci: fix build error for runtime
  .github/workflows/runtime.yml
  .github/workflows/test-cli.yml
  .github/workflows/test-verifier.yml
  CITATION.cff
  Makefile
  documents/build-and-test.md
Labels: size/M

#21 example: fix opensnoop
  .github/workflows/runtime.yml
  CITATION.cff
  Makefile
  README.md
  example/bootstrap/.gitignore
  example/bootstrap/Makefile
  example/bootstrap/README.md
  example/bootstrap/bootstrap.bpf.c
  example/bootstrap/bootstrap.c
  example/bootstrap/bootstrap.h
  example/bootstrap/syscall.txt
  example/opensnoop/README.md
  example/opensnoop/opensnoop.bpf.c
  example/opensnoop/opensnoop.c
  example/opensnoop/victim.cpp
  example/sslsniff/sslsniff.bpf.c
  example/sslsniff/sslsniff.c
Labels: size/XXL

#20 runtime: support map type `perf_event_array`
  example/perf-opensnoop/.gitignore
  example/perf-opensnoop/Makefile
  example/perf-opensnoop/README.md
  example/perf-opensnoop/opensnoop.bpf.c
  example/perf-opensnoop/opensnoop.c
  example/perf-opensnoop/opensnoop.h
  example/perf-opensnoop/victim.cpp
  example/statsnoop/.gitignore
  example/statsnoop/Makefile
  example/statsnoop/statsnoop.bpf.c
  example/statsnoop/statsnoop.c
  example/statsnoop/statsnoop.h
  example/statsnoop/victim.cpp
  runtime/CMakeLists.txt
  runtime/agent/agent.cpp
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/hash_map.cpp
  runtime/src/bpf_map/hash_map.hpp
  runtime/src/bpf_map/perf_event_array_map.cpp
  runtime/src/bpf_map/perf_event_array_map.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/epoll_handler.cpp
  runtime/src/handler/epoll_handler.hpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/src/handler/perf_event_handler.hpp
  runtime/syscall-server/CMakeLists.txt
  runtime/syscall-server/syscall_context.cpp
  runtime/syscall-server/syscall_context.hpp
  runtime/syscall-server/syscall_server_main.cpp
  runtime/syscall-server/syscall_server_utils.cpp
  runtime/syscall-server/syscall_server_utils.hpp
Labels: size/XXL

#25 Remove LD_PRELOAD env var after intializing syscall context
  runtime/syscall-server/syscall_context.hpp
Labels: size/XS

#27 Fix some issues that may cause sslsniff not working
  .gitignore
  runtime/agent/agent.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/array_map.cpp
  runtime/src/bpf_map/hash_map.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/syscall-server/syscall_server_utils.cpp
Labels: size/M

#30 Update "README.md" and "documents/build-and-test.md"
  README.md
  documents/build-and-test.md
Labels: size/S

#28 Make bpftrace work
  .gitignore
  benchmark/test_embed.c
  runtime/CMakeLists.txt
  runtime/agent-transformer/agent-transformer.cpp
  runtime/agent/agent.cpp
  runtime/include/bpf_attach_ctx.hpp
  runtime/include/bpftime_shm.hpp
  runtime/include/syscall_table.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/hash_map.cpp
  runtime/src/bpf_map/hash_map.hpp
  runtime/src/bpf_map/map_common_def.hpp
  runtime/src/bpf_map/per_cpu_array_map.cpp
  runtime/src/bpf_map/per_cpu_array_map.hpp
  runtime/src/bpf_map/per_cpu_hash_map.cpp
  runtime/src/bpf_map/per_cpu_hash_map.hpp
  runtime/src/bpftime_prog.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/map_handler.hpp
  runtime/src/handler/perf_event_handler.hpp
  runtime/src/syscall_table.cpp
  runtime/syscall-server/syscall_context.cpp
  runtime/syscall-server/syscall_context.hpp
  runtime/syscall-server/syscall_server_main.cpp
  runtime/syscall-server/syscall_server_utils.cpp
  runtime/test/include/test_minimal_bpf_host_ffi.h
  vm/include/ebpf_inst.h
  vm/llvm-jit/example/main-bpf-conformance.cpp
  vm/llvm-jit/example/main.cpp
  vm/llvm-jit/src/bpf_jit_compile_module.cpp
  vm/llvm-jit/src/bpf_jit_helpers.h
  vm/llvm-jit/src/ebpf_vm.cpp
  vm/simple-jit/ebpf_vm.c
Labels: size/XXL

#31 Fix a uretprobe issue
  example/.gitignore
  runtime/include/hook_entry.hpp
  runtime/src/attach/attach_internal.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/syscall-server/syscall_context.cpp
Labels: size/S

#33 examples: reorganize libbpf-tools
  .github/workflows/test-examples.yml
  README.md
  example/bash_readline/README.md
  example/libbpf-tools/bashreadline/.gitignore
  example/libbpf-tools/bashreadline/Makefile
  example/libbpf-tools/bashreadline/README.md
  example/libbpf-tools/bashreadline/readline.bpf.c
  example/libbpf-tools/bashreadline/readline.c
  example/libbpf-tools/bashreadline/readline.h
  example/libbpf-tools/opensnoop/.gitignore
  example/libbpf-tools/opensnoop/Makefile
  example/libbpf-tools/opensnoop/README.md
  example/libbpf-tools/opensnoop/opensnoop.bpf.c
  example/libbpf-tools/opensnoop/opensnoop.c
  example/libbpf-tools/opensnoop/opensnoop.h
  example/libbpf-tools/opensnoop/victim.cpp
  example/libbpf-tools/statsnoop/.gitignore
  example/libbpf-tools/statsnoop/Makefile
  example/libbpf-tools/statsnoop/README.md
  example/libbpf-tools/statsnoop/statsnoop.bpf.c
  example/libbpf-tools/statsnoop/statsnoop.c
  example/libbpf-tools/statsnoop/statsnoop.h
  example/libbpf-tools/statsnoop/victim.cpp
  example/perf-opensnoop/README.md
  runtime/syscall-server/syscall_server_utils.cpp
Labels: size/L

#36 runtime: fix an initializing bug when using attach mode
  runtime/agent/agent.cpp
Labels: size/S

#37 runtime: fix a double-free bug
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/ffi.cpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/test/CMakeLists.txt
  runtime/test/src/test_attach_hook.cpp
  runtime/test/src/test_attach_uprobe.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  vm/test/include/test_minimal_bpf_host_ffi.h
Labels: size/M

#38 runtime: add new test-framework for bpftime-runtime
  .github/workflows/test-runtime.yml
  Makefile
  runtime/CMakeLists.txt
  runtime/src/bpf_map/map_common_def.hpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/common_def.hpp
  runtime/unit-test/test_per_cpu_array.cpp
  runtime/unit-test/test_per_cpu_hash.cpp
Labels: size/L

#40 runtime: add syscall tracer
  runtime/bpftime-daemon/.gitignore
  runtime/bpftime-daemon/Makefile
  runtime/bpftime-daemon/README.md
  runtime/bpftime-daemon/bpf-mocker-event.h
  runtime/bpftime-daemon/bpf-mocker.bpf.c
  runtime/bpftime-daemon/bpf-mocker.cpp
  runtime/bpftime-daemon/bpf-utils.h
  runtime/bpftime-daemon/handle_bpf_event.cpp
  runtime/bpftime-daemon/handle_event.hpp
Labels: size/XXL

#43 Use cmake to build bpftime-daemon
  .github/workflows/runtime.yml
  .github/workflows/test-cli.yml
  .github/workflows/test-examples.yml
  .github/workflows/test-runtime.yml
  CMakeLists.txt
  cmake/libbpf.cmake
  runtime/CMakeLists.txt
  runtime/bpftime-daemon/CMakeLists.txt
Labels: size/M

#45 docs: improve README and fix docker
  .devcontainer/devcontainer.json
  Dockerfile
  README.md
Labels: size/M

#44 runtime: reconstruct bpf_attach_ctx
  CMakeLists.txt
  cmake/libbpf.cmake
  example/sslsniff/sslsniff.bpf.c
  runtime/CMakeLists.txt
  runtime/include/bpf_attach_ctx.hpp
  runtime/include/bpftime.hpp
  runtime/include/bpftime_ffi.hpp
  runtime/include/hook_entry.hpp
  runtime/object/CMakeLists.txt
  runtime/object/bpf_object.cpp
  runtime/object/bpftime_object.hpp
  runtime/src/attach/attach_internal.cpp
  runtime/src/attach/attach_internal.hpp
  runtime/src/attach/attach_manager/base_attach_manager.cpp
  runtime/src/attach/attach_manager/base_attach_manager.hpp
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/src/attach/attach_manager/frida_attach_manager.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/ffi.cpp
  runtime/test/CMakeLists.txt
  runtime/test/src/test_attach_filter.cpp
  runtime/test/src/test_attach_find_func_addr.cpp
  runtime/test/src/test_attach_hook.cpp
  runtime/test/src/test_attach_replace.cpp
  runtime/test/src/test_attach_uprobe.cpp
  runtime/test/src/test_ffi_register.cpp
  runtime/test/src/test_helpers.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/assets/ffi.bpf.h
  runtime/unit-test/assets/filter.bpf.c
  runtime/unit-test/assets/replace.bpf.c
  runtime/unit-test/assets/uprobe.bpf.c
  runtime/unit-test/attach/test_filter_attach.cpp
  runtime/unit-test/attach/test_function_address_resolve.cpp
  runtime/unit-test/attach/test_replace_attach.cpp
  runtime/unit-test/attach/test_uprobe_uretprobe.cpp
  runtime/unit-test/attach_with_ebpf/helper.hpp
  runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
  runtime/unit-test/attach_with_ebpf/test_attach_uprobe_with_ebpf.cpp
  runtime/unit-test/common_def.hpp
  tools/CMakeLists.txt
  tools/cli-rs/Cargo.lock
  tools/cli-rs/Cargo.toml
  tools/cli-rs/src/main.rs
  tools/cli/CMakeLists.txt
  tools/cli/main.cpp
  vm/simple-jit/ebpf_vm.c
Labels: size/XXL

#47 ci: add build and publish docker image
  .github/workflows/docker.yml
  Dockerfile
Labels: size/M

#49 runtime: implement Daemon tracing
  .github/workflows/docker.yml
  .github/workflows/test-runtime.yml
  CMakeLists.txt
  Dockerfile
  Makefile
  benchmark/uprobe/uprobe
  benchmark/uretprobe/uretprobe
  daemon/.gitignore
  daemon/CMakeLists.txt
  daemon/README.md
  daemon/bpf-mocker-event.h
  daemon/bpf-mocker.bpf.c
  daemon/bpf-mocker.cpp
  daemon/bpf-utils.h
  daemon/daemon.hpp
  daemon/daemon_config.hpp
  daemon/handle_bpf_event.cpp
  daemon/handle_bpf_event.hpp
  daemon/main.cpp
  documents/build-and-test.md
  runtime/CMakeLists.txt
  runtime/bpftime-daemon/bpf-mocker.cpp
  runtime/bpftime-daemon/handle_bpf_event.cpp
  runtime/bpftime-daemon/handle_event.hpp
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/map_common_def.hpp
  runtime/src/bpf_map/per_cpu_array_map.cpp
  runtime/src/bpf_map/per_cpu_hash_map.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/syscall-server/syscall_context.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/assets/uprobe.bpf.c
  runtime/unit-test/test_daemon.cpp
  tools/README.md
  tools/bpftimetool/CMakeLists.txt
  tools/bpftimetool/main.cpp
Labels: size/XXL

#51 runtime: add json import and export
  .github/workflows/runtime.yml
  .github/workflows/test-examples.yml
  .github/workflows/test-runtime.yml
  .github/workflows/test-verifier.yml
  .github/workflows/test-vm.yml
  CMakeLists.txt
  Makefile
  README.md
  cmake/StandardSettings.cmake
  daemon/main.cpp
  runtime/CMakeLists.txt
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_map/map_common_def.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/bpftime_shm_json.cpp
  runtime/src/bpftime_shm_json.hpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/syscall-server/syscall_context.cpp
  runtime/test/README.md
  runtime/test/bpf/.output/bpf/bpf.h
  runtime/test/bpf/.output/bpf/bpf_helper_defs.h
  runtime/test/bpf/.output/bpf/bpf_helpers.h
  runtime/test/bpf/.output/bpf/bpf_tracing.h
  runtime/test/bpf/.output/bpf/libbpf.h
  runtime/test/bpf/.output/bpf/libbpf_common.h
  runtime/test/bpf/.output/bpf/usdt.bpf.h
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/attach_with_ebpf/test_attach_uprobe_with_ebpf.cpp
  runtime/unit-test/maps/test_per_cpu_array.cpp
  runtime/unit-test/maps/test_per_cpu_hash.cpp
  runtime/unit-test/test_bpftime_shm_json.cpp
  runtime/unit-test/test_daemon.cpp
  third_party/json.hpp
  tools/CMakeLists.txt
  tools/bpftimetool/CMakeLists.txt
  tools/bpftimetool/main.cpp
Labels: size/XXL

#54 ci: Merge test-cli & test-example and Extend them to all examples
  .github/workflows/docker.yml
  .github/workflows/test-cli.yml
  .github/workflows/test-examples.yml
  .github/workflows/test-runtime.yml
  .github/workflows/test-vm.yml
  Dockerfile
Labels: size/L

#55 daemon: add doc and fix map type defs
  daemon/CMakeLists.txt
  daemon/README.md
  daemon/test/malloc.json
  daemon/user/handle_bpf_event.cpp
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_json.cpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/map_handler.hpp
  runtime/src/handler/perf_event_handler.hpp
  runtime/src/handler/prog_handler.hpp
  runtime/syscall-server/syscall_context.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/test/src/test_shm_server.cpp
Labels: size/L

#56 Update examples CI
  .github/workflows/test-examples.yml
Labels: size/M

#42 example: add gethostlatency
  example/libbpf-tools/gethostlatency/Makefile
  example/libbpf-tools/gethostlatency/README.md
  example/libbpf-tools/gethostlatency/gethostlatency.bpf.c
  example/libbpf-tools/gethostlatency/gethostlatency.c
  example/libbpf-tools/gethostlatency/gethostlatency.h
Labels: size/XL

#62 runtime: fix test for bad_alloc
  README.md
  daemon/README.md
  runtime/src/handler/handler_manager.hpp
Labels: size/S

#63 examples: add examples from bpftrace
  README.md
  example/bpftrace/README.md
  example/bpftrace/bashreadline.bt
  example/bpftrace/execsnoop.bt
  example/bpftrace/gethostlatency.bt
  example/bpftrace/killsnoop.bt
  example/bpftrace/opensnoop.bt
  example/bpftrace/sslsnoop.bt
  example/bpftrace/statsnoop.bt
  example/bpftrace/syncsnoop.bt
  example/bpftrace/syscount.bt
  example/bpftrace/threadsnoop.bt
Labels: size/L

#66 doc: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/L

#67 doc: Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/L
