Repository eunomia-bpf/bpftime, pull requests merged in 2024-09, with the labels that each got.

#346 fix: compile on old cmake version and add PATH
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/test-examples.yml
  README.md
  attach/base_attach_impl/CMakeLists.txt
  attach/frida_uprobe_attach_impl/CMakeLists.txt
  attach/syscall_trace_attach_impl/src/syscall_trace_attach_impl.cpp
  benchmark/CMakeLists.txt
  runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
  runtime/src/bpf_map/userspace/prog_array.cpp
  vm/CMakeLists.txt
Labels: size/M

#352 feat:add lcov and codecov support
  .github/workflows/test-attach.yml
  .github/workflows/test-runtime.yml
  .github/workflows/test-verifier.yml
  attach/frida_uprobe_attach_impl/CMakeLists.txt
  attach/syscall_trace_attach_impl/CMakeLists.txt
  bpftime-verifier/CMakeLists.txt
  runtime/unit-test/CMakeLists.txt
Labels: size/L

#350 docs: fix broken links in readme
  README.md
Labels: size/XS
