Repository eunomia-bpf/bpftime, pull requests merged in 2024-01, with the labels that each got.

#131 vm/runtime: implement userspace -> kernel tailcall
  .github/script/run_example.py
  .github/workflows/test-examples.yml
  .github/workflows/test-runtime.yml
  CMakeLists.txt
  Makefile
  daemon/CMakeLists.txt
  example/tailcall_minimal/.gitignore
  example/tailcall_minimal/Makefile
  example/tailcall_minimal/tailcall_minimal.bpf.c
  example/tailcall_minimal/tailcall_minimal.c
  example/tailcall_minimal/victim.c
  runtime/CMakeLists.txt
  runtime/agent/agent.cpp
  runtime/include/bpftime_shm.hpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/userspace/prog_array.cpp
  runtime/src/bpf_map/userspace/prog_array.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/map_handler.cpp
  runtime/syscall-server/syscall_context.cpp
  runtime/syscall-server/syscall_context.hpp
  runtime/syscall-server/syscall_server_utils.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/maps/test_kernel_user_hash.cpp
  runtime/unit-test/tailcall/test_user_to_kernel_tailcall.cpp
  tools/bpftimetool/CMakeLists.txt
  tools/cli-cpp/CMakeLists.txt
  tools/cli-cpp/main.cpp
  vm/cli/CMakeLists.txt
  vm/llvm-jit/src/llvm/compiler.cpp
  vm/llvm-jit/src/llvm/compiler_utils.cpp
  vm/llvm-jit/src/llvm/compiler_utils.hpp
  vm/simple-jit/ebpf_vm.c
Labels: size/XXL

#132 vm: fix cmpxchg in intepreter
  vm/simple-jit/ebpf_vm.c
Labels: size/M

#136 daemon: auto release `/a` when starting
  daemon/CMakeLists.txt
  daemon/assets/embedfile.c
  daemon/assets/placeholder
  daemon/user/bpf_tracer.cpp
Labels: size/M

#134 Github: Create FUNDING.yml
  .github/FUNDING.yml
Labels: size/S

#138 docs: move documents to website
  .devcontainer/devcontainer.json
  README.md
  documents/avaliable-features.md
  documents/bpftime-kernel.png
  documents/bpftime.md
  documents/bpftime.png
  documents/build-and-test.md
  documents/how-it-works.md
  documents/usage.md
  documents/userspace-ebpf-bpftime-lpc.pdf
Labels: size/L

#143 docker: remove rust toolchain
  Dockerfile
Labels: size/XS

#139 runtime: implement userspace USDT
  .github/workflows/test-examples.yml
  example/usdt_minimal/.gitignore
  example/usdt_minimal/Makefile
  example/usdt_minimal/README.md
  example/usdt_minimal/usdt_minimal.bpf.c
  example/usdt_minimal/usdt_minimal.c
  example/usdt_minimal/victim.cpp
  runtime/include/bpftime_prog.hpp
  runtime/include/bpftime_shm.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/attach/bpf_attach_syscall.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpftime_prog.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/bpftime_shm_json.cpp
  runtime/src/handler/handler_manager.cpp
  runtime/src/handler/prog_handler.cpp
  runtime/src/handler/prog_handler.hpp
  runtime/syscall-server/syscall_context.cpp
  runtime/syscall-server/syscall_server_main.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/unit-test/test_bpftime_shm_json.cpp
  vm/llvm-jit/src/llvm/compiler.cpp
  vm/test-runner/CMakeLists.txt
  vm/test-runner/main.cpp
Labels: size/XL

#146 Update FUNDING.yml
  .github/FUNDING.yml
Labels: size/XS

#150 docs: fix broken link in `README.md`
  README.md
Labels: size/XS

#154 vm: fix llvm as a standalone library
  .github/workflows/test-llvm-jit.yml
  CMakeLists.txt
  README.md
  vm/CMakeLists.txt
  vm/Makefile
  vm/README.md
  vm/cli/main.cpp
  vm/llvm-jit/.gitignore
  vm/llvm-jit/CMakeLists.txt
  vm/llvm-jit/Makefile
  vm/llvm-jit/README.md
  vm/llvm-jit/example/main-bpf-conformance.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.cpp
  vm/llvm-jit/unit-test/llvm-aot.cpp
Labels: size/L

#151 Attempt to add arm64 support
  Makefile
  benchmark/test_embed.c
  example/malloc/malloc.c
  example/tailcall_minimal/tailcall_minimal.c
  example/usdt_minimal/victim.cpp
  runtime/agent-transformer/text_segment_transformer.cpp
  runtime/src/attach/attach_internal.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/attach/bpf_attach_syscall.cpp
  runtime/src/bpf_map/userspace/prog_array.cpp
  runtime/src/bpf_map/userspace/ringbuf_map.cpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/unit-test/attach/test_filter_attach_with_override.cpp
  runtime/unit-test/attach/test_replace_attach_with_override.cpp
  runtime/unit-test/attach/test_uprobe_uretprobe.cpp
Labels: size/L

#164 docs: fix document error for new cli
  example/bpftrace/README.md
  example/minimal/README.md
Labels: size/XS

#161 ci: make all tests run under fedora(AOT & runtime)
  .github/workflows/test-aot-cli.yml
  .github/workflows/test-runtime.yml
  daemon/test/CMakeLists.txt
  runtime/src/bpf_map/userspace/prog_array.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/attach/test_filter_attach_with_override.cpp
  runtime/unit-test/attach/test_replace_attach_with_override.cpp
  runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
  runtime/unit-test/tailcall/test_user_to_kernel_tailcall.cpp
  vm/llvm-jit/CMakeLists.txt
  vm/llvm-jit/unit-test/CMakeLists.txt
Labels: size/L

#182 Capture remaining arguments for bpftime start
  tools/cli-cpp/main.cpp
Labels: size/XS

#200 cli: Support set spdlog log level by using env for bpftime cli
  tools/cli-cpp/main.cpp
  vm/cli/main.cpp
Labels: size/XS

#193 runtime: add ufunc support
  .vscode/launch.json
  example/patch/redis/ffi.bpf.h
  example/patch/redis/redis-patch.bpf.c
  example/patch/redis/ufunc.bpf.h
  example/patch/vim/README.md
  example/patch/vim/poc.bpf.c
  runtime/CMakeLists.txt
  runtime/extension/extension_helper.cpp
  runtime/include/bpftime.hpp
  runtime/include/bpftime_config.hpp
  runtime/include/bpftime_ffi.hpp
  runtime/include/bpftime_helper_group.hpp
  runtime/include/bpftime_prog.hpp
  runtime/include/bpftime_ufunc.hpp
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpftime_internal.h
  runtime/src/bpftime_shm.cpp
  runtime/src/ufunc.cpp
  runtime/syscall-server/syscall_server_utils.cpp
  runtime/test/CMakeLists.txt
  runtime/test/bpf/ffi-btf.bpf.c
  runtime/test/bpf/ffi.bpf.h
  runtime/test/bpf/replace.bpf.c
  runtime/test/bpf/ufunc.bpf.c
  runtime/test/bpf/ufunc.bpf.h
  runtime/test/include/test_bpf_progs.h
  runtime/test/include/test_minimal_bpf_host_ufunc.h
  runtime/test/src/test_attach_replace.cpp
  runtime/test/src/test_hash_map.c
  runtime/test/src/test_helpers.cpp
  runtime/test/src/test_shm_client.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/test/src/test_ufunc.cpp
  runtime/test/src/test_ufunc_register.cpp
  runtime/unit-test/assets/ffi.bpf.h
  runtime/unit-test/assets/filter.bpf.c
  runtime/unit-test/assets/replace.bpf.c
  runtime/unit-test/assets/ufunc.bpf.h
  runtime/unit-test/attach_with_ebpf/test_attach_filter_with_ebpf.cpp
  vm/example/bpf_progs.h
  vm/llvm-jit/example/bpf_progs.h
  vm/test/include/test_bpf_progs.h
  vm/test/include/test_minimal_bpf_host_ufunc.h
  vm/test/src/test_core_minimal_ffi.c
Labels: size/XXL

#192 ci: make all tests run under fedora(llvm-jit, examples, vm)
  .github/workflows/test-examples.yml
  .github/workflows/test-llvm-jit.yml
  .github/workflows/test-vm.yml
Labels: size/L

#206 runtime: fix bpf link error in other attach types
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  LICENSE
  Makefile
  README.md
  cmake/StandardSettings.cmake
  runtime/include/bpftime.hpp
  runtime/include/bpftime_shm.hpp
  runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/bpftime_shm_json.cpp
  runtime/src/handler/link_handler.hpp
  runtime/syscall-server/syscall_context.cpp
  runtime/syscall-server/syscall_context.hpp
  runtime/unit-test/test_bpftime_shm_json.cpp
Labels: size/L
