Repository eunomia-bpf/bpftime, pull requests merged in 2024-05, with the labels that each got.

#288 fix: fix segmentation fault about bashreadline
  attach/frida_uprobe_attach_impl/include/frida_attach_private_data.hpp
  attach/frida_uprobe_attach_impl/src/frida_attach_private_data.cpp
  attach/frida_uprobe_attach_impl/src/frida_uprobe_attach_impl.cpp
  tools/bpftimetool/main.cpp
Labels: size/M

#290 fix: using the openssl resolved path in sslsniff
  example/sslsniff/sslsniff.c
Labels: size/XS

#293 Update README.md
  example/bpftrace/README.md
Labels: size/XS

#295 fix: bash stucks when injected by bpftime agent
  attach/text_segment_transformer/agent-transformer.cpp
  example/libbpf-tools/bashreadline/readline.bpf.c
  runtime/agent/agent.cpp
  runtime/src/bpftime_shm_internal.cpp
Labels: size/S

#294 Add libbpftime.a archive when BPFTIME_BUILD_STATIC_LIB option is provided
  CMakeLists.txt
  Makefile
  cmake/StandardSettings.cmake
  cmake/extract_and_rename.sh
  example/libbpftime_example/Makefile
  example/libbpftime_example/README.md
  example/libbpftime_example/ebpf.json
  example/libbpftime_example/main.cpp
  runtime/CMakeLists.txt
Labels: size/L

#297 runtime: add network related helpers and maps
  runtime/extension/userspace_xdp.h
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/userspace/map_in_maps.hpp
  runtime/src/handler/map_handler.cpp
Labels: size/L

#298 fix: remove memory allocation in hash maps
  runtime/src/bpf_map/map_common_def.hpp
  runtime/src/bpf_map/userspace/hash_map.cpp
  runtime/src/bpf_map/userspace/hash_map.hpp
  runtime/src/bpf_map/userspace/map_in_maps.hpp
  runtime/src/bpf_map/userspace/per_cpu_array_map.cpp
  runtime/src/bpf_map/userspace/per_cpu_hash_map.cpp
  runtime/src/bpf_map/userspace/per_cpu_hash_map.hpp
  runtime/src/bpf_map/userspace/prog_array.cpp
Labels: size/L

#300 Update README.md
  tools/aot/README.md
Labels: size/XS
