Repository eunomia-bpf/bpftime, pull requests merged in 2024-02, with the labels that each got.

#207 vm: fix compile error on g++ 10.3.1
  vm/llvm-jit/example/main-bpf-conformance.cpp
Labels: size/XS

#204 ci: Fix CMakeLists.txt for llvm-jit to allow user define the llvm path
  .github/workflows/test-aot-cli.yml
  .github/workflows/test-examples.yml
  .github/workflows/test-llvm-jit.yml
  .github/workflows/test-vm.yml
  vm/llvm-jit/CMakeLists.txt
Labels: size/M

#209 build in parallel in makefile
  Makefile
  vm/Makefile
Labels: size/L

#215 test: use Catch2 and cmake for runtime tests
  .github/workflows/test-runtime.yml
  runtime/src/attach/attach_manager/base_attach_manager.cpp
  runtime/src/attach/attach_manager/frida_attach_manager.cpp
  runtime/test/CMakeLists.txt
  runtime/test/src/test_attach_replace.cpp
  runtime/test/src/test_shm_hash_maps.cpp
  runtime/test/src/test_shm_progs_attach.cpp
  runtime/test/src/test_ufunc_register.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/assets/helpers.bpf.c
  runtime/unit-test/assets/replace.bpf.c
  runtime/unit-test/assets/ufunc.bpf.c
  runtime/unit-test/assets/ufunc.bpf.h
  runtime/unit-test/attach_with_ebpf/test_attach_replace.cpp
  runtime/unit-test/attach_with_ebpf/test_helpers.cpp
  runtime/unit-test/attach_with_ebpf/test_shm_progs_attach.cpp
  runtime/unit-test/attach_with_ebpf/test_ufunc_register.cpp
  runtime/unit-test/maps/test_shm_hash_maps.cpp
  vm/Makefile
Labels: size/XXL

#216 CI: clean the CI workflow by using Dockerfile
  .github/workflows/build-benchmarks.yml
  .github/workflows/docker.yml
  .github/workflows/test-aot-cli.yml
  .github/workflows/test-examples.yml
  .github/workflows/test-llvm-jit.yml
  .github/workflows/test-runtime.yml
  .github/workflows/test-verifier.yml
  .github/workflows/test-vm.yml
  Dockerfile.fedora
  Dockerfile.ubuntu
Labels: size/L

#220 ci: Release binary with RelWithDebInfo and support "no-omit-frame-pointer" to keep the frame pointer
  CMakeLists.txt
  Makefile
Labels: size/S

#222 cli: remove rust depreciate code
  tools/cli-rs-archive/.gitignore
  tools/cli-rs-archive/Cargo.lock
  tools/cli-rs-archive/Cargo.toml
  tools/cli-rs-archive/build.rs
  tools/cli-rs-archive/src/frida.rs
  tools/cli-rs-archive/src/main.rs
Labels: size/L

#225 fix: Updated link in the contributor guidelines
  CONTRIBUTING.md
Labels: size/XS

#227 vm: remove aot cache for security issues
  vm/llvm-jit/CMakeLists.txt
  vm/llvm-jit/src/llvm/llvm_jit_context.cpp
Labels: size/L

#229 runtime: add map_ops support
  runtime/include/bpftime_config.hpp
  runtime/include/bpftime_shm.hpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/map_handler.cpp
  runtime/src/handler/map_handler.hpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/maps/test_external_map_ops.cpp
  runtime/unit-test/maps/test_shm_hash_maps.cpp
Labels: size/L

#241 #237 | hp77 | Make registers arch independent
  attach/frida_uprobe_attach_impl/test/test_attach_with_unified_interface.cpp
Labels: size/XS
