Repository eunomia-bpf/bpftime, pull requests merged in 2024-04, with the labels that each got.

#263 runtime: make LLVM JIT Compiled by default
  CMakeLists.txt
  Dockerfile
  Makefile
Labels: size/XS

#264 runtime/agent: implement detaching
  attach/frida_uprobe_attach_impl/src/frida_internal_attach_entry.cpp
  attach/text_segment_transformer/agent-transformer.cpp
  runtime/agent/agent.cpp
  runtime/include/bpf_attach_ctx.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/handler_manager.hpp
  tools/cli/CMakeLists.txt
  tools/cli/main.cpp
  vm/llvm-jit/include/llvm_bpf_jit.h
Labels: size/L

#276 fix issue Unable to build on newer LLVM #268
  bpftime-verifier/test/simple.cpp
  cmake/libbpf.cmake
  example/error-inject/Makefile
  example/goroutine/Makefile
  example/libbpf-tools/bashreadline/Makefile
  example/libbpf-tools/funclatency/Makefile
  example/libbpf-tools/gethostlatency/Makefile
  example/libbpf-tools/mountsnoop/Makefile
  example/libbpf-tools/opensnoop/Makefile
  example/libbpf-tools/sigsnoop/Makefile
  example/libbpf-tools/statsnoop/Makefile
  example/libbpf-tools/syscount/Makefile
  example/malloc/Makefile
  example/minimal/Makefile
  example/opensnoop/Makefile
  example/patch/redis/Makefile
  example/sslsniff/Makefile
  example/tailcall_minimal/Makefile
  example/usdt_minimal/Makefile
  runtime/test/bpf/Makefile
  runtime/test/include/test_bpf_progs.h
  tools/aot/example/Makefile
  vm/llvm-jit/CMakeLists.txt
  vm/llvm-jit/src/llvm/compiler.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.hpp
  vm/test/include/test_bpf_progs.h
  vm/tools/compile_code.py
Labels: size/L

#278 fix: #185 The bpftime build system won't rebuild libbpf when libbpf's…
  cmake/libbpf.cmake
Labels: size/XS

#284 Add feature Use std::chrono instead of clock_gettime
  CMakeLists.txt
  Makefile
  daemon/user/bpf_tracer.cpp
  runtime/src/bpf_helper.cpp
  tools/bpftimetool/main.cpp
Labels: size/M

#286 Make llvm-jit work with bpftrace
  vm/llvm-jit/CMakeLists.txt
Labels: size/XS
