Repository eunomia-bpf/bpftime, pull requests merged in 2024-03, with the labels that each got.

#245 refactor: Make base_attach_impl into a header-only library fix #233
  attach/base_attach_impl/CMakeLists.txt
  attach/base_attach_impl/attach_private_data.cpp
  attach/base_attach_impl/attach_private_data.hpp
  attach/base_attach_impl/base_attach_impl.cpp
  attach/base_attach_impl/base_attach_impl.hpp
Labels: size/L

#244 bpftimetool: fixes unnecessary report of shm removed when there's nothing to remove
  runtime/src/bpftime_shm_internal.cpp
Labels: size/XS

#240 workflow to run attach tests
  .github/workflows/test-attach.yml
  .github/workflows/test-llvm-jit.yml
Labels: size/M

#249 runtime: support attach arguments of custom attach implementations, and add an example
  CMakeLists.txt
  example/attach_implementation/.gitignore
  example/attach_implementation/CMakeLists.txt
  example/attach_implementation/README.md
  example/attach_implementation/controller/controller.cpp
  example/attach_implementation/controller/request_filter.bpf.c
  example/attach_implementation/controller/request_filter.h
  example/attach_implementation/nginx.conf
  example/attach_implementation/nginx_plugin/.clangd
  example/attach_implementation/nginx_plugin/config
  example/attach_implementation/nginx_plugin/ngx_http_bpftime_module.c
  example/attach_implementation/nginx_plugin_adaptor/nginx_plugin_adaptor.cpp
  runtime/include/bpftime_shm.hpp
  runtime/object/CMakeLists.txt
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpf_map/userspace/ringbuf_map.cpp
  runtime/src/bpf_map/userspace/ringbuf_map.hpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/bpftime_shm_internal.hpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/src/handler/perf_event_handler.hpp
Labels: size/XL

#255 runtime: fix per cpu map low performance
  runtime/src/bpf_map/map_common_def.hpp
  runtime/src/bpf_map/userspace/prog_array.hpp
Labels: size/S

#256 runtime: Add cmake options to control build runtime interact with kernel map
  .gitignore
  cmake/StandardSettings.cmake
  cmake/frida.cmake
  runtime/CMakeLists.txt
Labels: size/M

#257 tools: add support for AOT cli
  example/minimal/uprobe.bpf.c
  runtime/include/bpftime_prog.hpp
  tools/CMakeLists.txt
  tools/aot/CMakeLists.txt
  tools/aot/README.md
  tools/aot/example/.gitignore
  tools/aot/example/Makefile
  tools/aot/example/do_count.o
  tools/aot/example/do_uprobe_trace.o
  tools/aot/example/main.c
  tools/aot/example/malloc.json
  tools/aot/main.cpp
  tools/cli/CMakeLists.txt
  tools/cli/main.cpp
  vm/llvm-jit/include/llvm_bpf_jit.h
  vm/llvm-jit/src/llvm/llvm_jit_context.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.hpp
Labels: size/XL

#260 runtime/agent: Add top level exception handlers
  attach/frida_uprobe_attach_impl/src/frida_attach_utils.cpp
  attach/syscall_trace_attach_impl/src/syscall_table.cpp
  attach/syscall_trace_attach_impl/src/syscall_trace_attach_impl.cpp
  attach/text_segment_transformer/agent-transformer.cpp
  runtime/agent/agent.cpp
  runtime/extension/extension_helper.cpp
  runtime/src/bpf_helper.cpp
  runtime/src/bpf_map/shared/perf_event_array_kernel_user.cpp
  runtime/src/bpf_map/userspace/perf_event_array_map.cpp
  runtime/src/bpf_map/userspace/prog_array.cpp
  runtime/src/bpf_map/userspace/ringbuf_map.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/handler/handler_manager.cpp
  runtime/src/handler/map_handler.hpp
  runtime/src/handler/perf_event_handler.cpp
  runtime/src/ufunc.cpp
Labels: size/L
