Repository eunomia-bpf/bpftime, pull requests merged in 2024-08, with the labels that each got.

#299 Fix performance: use new hash map implement
  runtime/CMakeLists.txt
  runtime/src/bpf_map/bpftime_hash_map.hpp
  runtime/src/bpf_map/userspace/fix_hash_map.cpp
  runtime/src/bpf_map/userspace/fix_hash_map.hpp
  runtime/src/bpf_map/userspace/var_hash_map.cpp
  runtime/src/bpf_map/userspace/var_hash_map.hpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/src/handler/map_handler.cpp
  runtime/unit-test/CMakeLists.txt
  runtime/unit-test/attach_with_ebpf/test_shm_progs_attach.cpp
  runtime/unit-test/maps/test_bpftime_hash_map.cpp
Labels: size/XL

#285 Allow defining shared memory size at runtime
  daemon/user/bpftime_driver.cpp
  runtime/CMakeLists.txt
  runtime/include/bpftime_config.hpp
  runtime/include/bpftime_shm.hpp
  runtime/src/bpftime_config.cpp
  runtime/src/bpftime_shm.cpp
  runtime/src/bpftime_shm_internal.cpp
  runtime/syscall-server/syscall_server_utils.cpp
  tools/bpftimetool/main.cpp
Labels: size/L

#317 Fix: debug log cannot be print when build in debug mode
  CMakeLists.txt
  Makefile
  attach/CMakeLists.txt
  runtime/src/bpftime_shm_internal.cpp
Labels: size/S

#323 llvm-jit: patch lddw helpers at compile time
  vm/llvm-jit/src/compat/compat_llvm.cpp
  vm/llvm-jit/src/llvm/compiler.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.cpp
  vm/llvm-jit/src/llvm/llvm_jit_context.hpp
Labels: size/L

#321 fix: improve error message and handling in syscall-server
  .github/workflows/build-benchmarks.yml
  .gitignore
  attach/frida_uprobe_attach_impl/src/frida_attach_utils.cpp
  attach/frida_uprobe_attach_impl/src/frida_uprobe_attach_impl.cpp
  benchmark/.gitignore
  benchmark/Makefile
  benchmark/README.md
  benchmark/run_benchmark.py
  runtime/agent/agent.cpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/bpftime_prog.cpp
  runtime/syscall-server/CMakeLists.txt
  runtime/syscall-server/syscall_server_main.cpp
  tools/bpftimetool/README.md
  vm/compat/include/bpftime_vm_compat.hpp
Labels: size/L

#334 bench: add new micro benchmark about maps and read/write userspace memory
  Makefile
  benchmark/.gitignore
  benchmark/README.md
  benchmark/hash_map/.gitignore
  benchmark/hash_map/Makefile
  benchmark/hash_map/README.md
  benchmark/hash_map/uprobe.bpf.c
  benchmark/hash_map/uprobe.c
  benchmark/run_benchmark.py
  benchmark/syscount/Makefile
  benchmark/syscount/read-sendmsg.c
  benchmark/syscount/test.sh
  benchmark/syscount/testfile.txt
  benchmark/test.c
  benchmark/test_embed.c
  benchmark/tools/.gitignore
  benchmark/tools/Makefile
  benchmark/tools/driving.py
  benchmark/tools/fig.py
  benchmark/tools/readlink.cpp
  benchmark/uprobe/uprobe-override.c
  benchmark/uprobe/uprobe.bpf.c
  benchmark/uprobe/uprobe.c
  example/minimal/README.md
  runtime/src/bpf_map/userspace/per_cpu_array_map.cpp
Labels: size/XXL

#339 add xdp-counter example
  .github/workflows/test-examples.yml
  example/Makefile
  example/xdp-counter/.gitignore
  example/xdp-counter/Makefile
  example/xdp-counter/README.md
  example/xdp-counter/base.btf
  example/xdp-counter/xdp-counter.bpf.c
  example/xdp-counter/xdp-counter.c
Labels: size/L
