Repository eunomia-bpf/bpftime, pull requests merged in 2025-05, with the labels that each got.

#393 Add simple attach impl to provide simpler way to register some basic attach impls
  .github/script/run_nginx_attach_example.py
  .github/workflows/test-nginx-attach.yml
  attach/CMakeLists.txt
  attach/simple_attach_impl/CMakeLists.txt
  attach/simple_attach_impl/simple_attach_impl.cpp
  attach/simple_attach_impl/simple_attach_impl.hpp
  example/attach_implementation/CMakeLists.txt
  example/attach_implementation/controller/controller.cpp
  example/attach_implementation/nginx_plugin_adaptor/nginx_plugin_adaptor.cpp
  runtime/CMakeLists.txt
Labels: size/XL

#395 Fix a typo in README [skip ci]
  README.md
Labels: size/XS

#399 benchmark: add new visualization script for performance metrics
  .gitignore
  example/attach_implementation/benchmark/README.md
  example/attach_implementation/benchmark/example_benchmark_results.json
  example/attach_implementation/benchmark/run_benchmark.py
  example/attach_implementation/benchmark/visualization.py
Labels: size/L
