Repository eunomia-bpf/bpftime, pull requests merged in 2025-10, with the labels that each got.

#453 enhances the CUDA benchmarking and add memtrace
  .gitignore
  README.md
  benchmark/cuda/README.md
  benchmark/gpu/.gitignore
  benchmark/gpu/Makefile
  benchmark/gpu/README.md
  benchmark/gpu/cuda_probe.bpf.c
  benchmark/gpu/cuda_probe.c
  benchmark/gpu/nvbit_timing_funcs.cu
  benchmark/gpu/nvbit_vec_add.cu
  benchmark/gpu/run_cuda_bench.py
  benchmark/gpu/vec_add.cu
  example/gpu/README.md
  example/gpu/cuda-counter-gpu-array/README.md
  example/gpu/cuda-counter-gpu-ringbuf/README.md
  example/gpu/cuda-counter/README.md
  example/gpu/mem_trace/.gitignore
  example/gpu/mem_trace/Makefile
  example/gpu/mem_trace/README.md
  example/gpu/mem_trace/mem_trace.bpf.c
  example/gpu/mem_trace/mem_trace.c
  example/gpu/mem_trace/vec_add.cu
  installation.md
Labels: size/XXL

#455 gpu: fix memtrace example
  attach/nv_attach_impl/nv_attach_impl.cpp
  attach/nv_attach_impl/nv_attach_impl_patcher.cpp
  example/gpu/cuda-counter/cuda_probe.bpf.c
  example/gpu/kernelretsnoop/kernelretsnoop.bpf.c
  example/gpu/launchlate/launchlate.bpf.c
  example/gpu/mem_trace/mem_trace.bpf.c
  example/gpu/threadhist/threadhist.bpf.c
  runtime/include/bpftime_prog.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
Labels: size/M

#448 [WIP] Force link VM compat libraries to avoid runtime error in openeuler
  .github/workflows/test-bpftrace.yml
  .github/workflows/test-runtime.yml
  example/attach_implementation/CMakeLists.txt
  example/attach_implementation/controller/CMakeLists.txt
  runtime/CMakeLists.txt
  runtime/agent/CMakeLists.txt
  runtime/syscall-server/CMakeLists.txt
  tools/cli/CMakeLists.txt
  tools/cli/main.cpp
  vm/compat/llvm-vm/CMakeLists.txt
  vm/compat/ubpf-vm/CMakeLists.txt
  vm/vm-core/CMakeLists.txt
Labels: size/L

#456 Allow directly running eBPF program on GPU
  attach/base_attach_impl/attach_private_data.hpp
  attach/nv_attach_impl/nv_attach_impl.cpp
  attach/nv_attach_impl/nv_attach_impl.hpp
  attach/nv_attach_impl/nv_attach_impl_patcher.cpp
  attach/nv_attach_impl/nv_attach_private_data.hpp
  example/gpu/directly_run_on_gpu/.gitignore
  example/gpu/directly_run_on_gpu/Makefile
  example/gpu/directly_run_on_gpu/README.md
  example/gpu/directly_run_on_gpu/directly_run.bpf.c
  example/gpu/directly_run_on_gpu/directly_run.c
  runtime/include/bpf_attach_ctx.hpp
  runtime/src/attach/bpf_attach_ctx.cpp
  runtime/src/attach/bpf_attach_ctx_cuda.cpp
  tools/bpftimetool/main.cpp
Labels: size/XL
